- name: Enable USB storage
  hosts: all
  become: yes

  tasks:

    - name: Remove blacklist
      file:
        path: /etc/modprobe.d/disable-usb-storage.conf
        state: absent

    - name: Load usb-storage module
      command: modprobe usb-storage

    - name: Update initramfs
      command: update-initramfs -u
