- name: Enforce install policy from FreeIPA
  hosts: all
  become: yes

  tasks:

    - name: Clear SSSD cache
      command: sss_cache -E

    - name: Restart SSSD
      service:
        name: sssd
        state: restarted

    # SNAP CHECK
    - name: Check snap binary
      stat:
        path: /usr/bin/snap
      register: snap_bin

    - name: Restrict snap to program_install group
      file:
        path: /usr/bin/snap
        owner: root
        group: program_install
        mode: '0750'
      when: snap_bin.stat.exists

    # FLATPAK CHECK
    - name: Check flatpak binary
      stat:
        path: /usr/bin/flatpak
      register: flatpak_bin

    - name: Restrict flatpak to program_install group
      file:
        path: /usr/bin/flatpak
        owner: root
        group: program_install
        mode: '0750'
      when: flatpak_bin.stat.exists
